language: csharp
install:
  # Restore nuget packages
  - nuget restore Pixie.sln

script:
  # Build Pixie.
  - msbuild /p:Configuration=Release /verbosity:quiet /nologo Pixie.sln

  # Run the examples.
  - mono ./Examples/CaretDiagnostics/bin/Release/CaretDiagnostics.exe
  - mono ./Examples/FormattedList/bin/Release/FormattedList.exe
  - mono ./Examples/LoycInterop/bin/Release/LoycInterop.exe
  - mono ./Examples/ParseOptions/bin/Release/ParseOptions.exe a.txt -fno-syntax-only --files -O1 -Ofast b.txt --files=c.txt - -- -v
  - mono ./Examples/PrintHelp/bin/Release/PrintHelp.exe
  - mono ./Examples/SimpleErrorMessage/bin/Release/SimpleErrorMessage.exe

  # Run the tests
  - mono ./Tests/bin/Release/Tests.exe
