exe:
	make -C CaretDiagnostics exe
	make -C FormattedList exe

all:
	make -C CaretDiagnostics all
	make -C FormattedList all

flo:
	make -C CaretDiagnostics flo
	make -C FormattedList flo

clean:
	make -C CaretDiagnostics clean
	make -C FormattedList clean
