exe:
	make -C CaretDiagnostics exe
	make -C FormattedList exe
	make -C LoycInterop exe
	make -C ParseOptions exe
	make -C PrintHelp exe
	make -C SimpleErrorMessage exe

all:
	make -C CaretDiagnostics all
	make -C FormattedList all
	make -C LoycInterop all
	make -C ParseOptions all
	make -C PrintHelp all
	make -C SimpleErrorMessage all

flo:
	make -C CaretDiagnostics flo
	make -C FormattedList flo
	make -C LoycInterop flo
	make -C ParseOptions flo
	make -C PrintHelp flo
	make -C SimpleErrorMessage flo

clean:
	make -C CaretDiagnostics clean
	make -C FormattedList clean
	make -C LoycInterop clean
	make -C ParseOptions cle
	make -C PrintHelp clean
	make -C SimpleErrorMessage clean
