exe:
	make -C CaretDiagnostics exe
	make -C FormattedList exe
	make -C ParseOptions exe
	make -C PrintHelp exe

all:
	make -C CaretDiagnostics all
	make -C FormattedList all
	make -C ParseOptions all
	make -C PrintHelp all

flo:
	make -C CaretDiagnostics flo
	make -C FormattedList flo
	make -C ParseOptions flo
	make -C PrintHelp flo

clean:
	make -C CaretDiagnostics clean
	make -C FormattedList clean
	make -C ParseOptions cle
	make -C PrintHelp clean
